# -*- coding: utf-8 -*-
"""Rejection_emails.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yvtrzmQ1A1-EF-7hvpe9U1esoKiWcehl
"""

import pandas as pd
import json
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt')
import re

# Read the JSON file
data = pd.read_json('/content/emails.json')

data.head(5)

#concatenate all the strings into one string using space as a separator
text = ' '.join(data['email_body'])

# Convert text to lowercase
text = text.lower()

# Remove punctuation
text = text.translate(str.maketrans('', '', string.punctuation))

# Tokenize the text
tokens = word_tokenize(text)

# Remove stopwords
stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word not in stop_words]

# Join the tokens back into text
preprocessed_text = ' '.join(filtered_tokens)

def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

clean_text = remove_html_tags(preprocessed_text)

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)

plt.figure(figsize=(10, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()